### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [roothorick/WineOpenVR#3]
ld: Relocatable linking with relocations from format elf32-i386 (/usr/lib/i386-linux-gnu/wine/libwinecrt0.a(dll_entry.o)) to format elf64-x86-64 (openvr_api.Ani27n.o) is not supported
winebuild: ld failed with status 1
winegcc: /usr/lib/wine/winebuild failed
Makefile:110: recipe for target 'bin64/openvr_api.dll.so' failed
make: *** [bin64/openvr_api.dll.so] Error 2

cannot install both wine32-tools wine32-development-tools AND wine64-tools wine64-development-tools.
I'm guessing this is related to the compile error here ?

**Comment by roothorick** [comment]
What distro? I suspect it's a packaging issue on their end. The current git master should compile fine in Ubuntu 16.04

**Comment by roothorick** [comment]
Oh! Forgot something. wine-staging will ultimately be required due to the planned Direct3D support relying on Vulkan. So, try the wine-staging packages from the official Wine PPA, explained here:

https://wiki.winehq.org/Ubuntu

**Comment by ghost** [comment]
Okay, Oh, I'm on 17.04

On the other hand, would it be possible for you to add the instructions on what packages/ppa's are needed to the README.md?

Also, it's looking or the d3d11.h headder

**Comment by roothorick** [comment]
d3d11.h should come from Wine. Nothing in the master branch needs it... yet. You can comment out the include just to get what's here so far up and running for now.

I want to hold off on expanding the readme until the D3D proxy has taken shape to the point of knowing what the dependencies and any possible compilation complications will be. The extreme rarity of non-D3D VR apps makes this pretty pointless for users, and a developer capable of making any real headway on the D3D proxy should be able to piece things together themselves.

(PS: Yes, development is stalled, but not for not trying. I knew far less about computer graphics than I thought I did. What's happening now when I find time is basically me learning how Vulkan and D3D work.)

**Comment by ghost** [comment]
Ah, that's a good way to go!
It looks like it almost compiled this time after commenting out d3d11.h:

ld: Relocatable linking with relocations from format elf64-x86-64 (/opt/wine-stable/lib64/wine/libwinecrt0.a(dll_entry.o)) to format elf32-i386 (openvr_api.qOQRGz.o) is not supported
winebuild: ld failed with status 1
winegcc: winebuild failed
Makefile:107: recipe for target 'bin32/openvr_api.dll.so' failed
make: *** [bin32/openvr_api.dll.so] Error 2

**Comment by roothorick** [comment]
It's not finding the 32bit libwinecrt0.a for some reason.

Do you have both wine-stable-amd64 and wine-stable-i386:i386 installed?

What's the full command that produces that error?

**Comment by ghost** [comment]
`wineg++ -c -m32 -Isrc -o bin32/ivrscreenshots/ivrscreenshots_001.o src/ivrscreenshots/ivrscreenshots_001.cpp
wineg++ -c -m32 -Isrc -o bin32/ivrresources/ivrresources_001.o src/ivrresources/ivrresources_001.cpp
wineg++ -c -m32 -Isrc -o bin32/ivrdrivermanager/ivrdrivermanager_001.o src/ivrdrivermanager/ivrdrivermanager_001.cpp
wineg++ src/openvr_api.spec -o bin32/openvr_api.dll.so bin32/wovr_exports.o bin32/d3dproxy.o bin32/ivrsystem/ivrsystem_009.o bin32/ivrsystem/ivrsystem_010.o bin32/ivrsystem/ivrsystem_011.o bin32/ivrsystem/ivrsystem_012.o bin32/ivrsystem/ivrsystem_014.o bin32/ivrsystem/ivrsystem_015.o bin32/ivrsystem/ivrsystem_016.o bin32/ivrapplications/ivrapplications_002.o bin32/ivrapplications/ivrapplications_003.o bin32/ivrapplications/ivrapplications_004.o bin32/ivrapplications/ivrapplications_005.o bin32/ivrapplications/ivrapplications_006.o bin32/ivrsettings/ivrsettings_001.o bin32/ivrsettings/ivrsettings_002.o bin32/ivrchaperone/ivrchaperone_003.o bin32/ivrchaperonesetup/ivrchaperonesetup_004.o bin32/ivrchaperonesetup/ivrchaperonesetup_005.o bin32/ivrcompositor/ivrcompositor_011.o bin32/ivrcompositor/ivrcompositor_012.o bin32/ivrcompositor/ivrcompositor_013.o bin32/ivrcompositor/ivrcompositor_014.o bin32/ivrcompositor/ivrcompositor_015.o bin32/ivrcompositor/ivrcompositor_016.o bin32/ivrcompositor/ivrcompositor_018.o bin32/ivrcompositor/ivrcompositor_019.o bin32/ivrcompositor/ivrcompositor_020.o bin32/ivrnotifications/ivrnotifications_002.o bin32/ivroverlay/ivroverlay_008.o bin32/ivroverlay/ivroverlay_010.o bin32/ivroverlay/ivroverlay_011.o bin32/ivroverlay/ivroverlay_012.o bin32/ivroverlay/ivroverlay_013.o bin32/ivroverlay/ivroverlay_014.o bin32/ivroverlay/ivroverlay_016.o bin32/ivrrendermodels/ivrrendermodels_002.o bin32/ivrrendermodels/ivrrendermodels_004.o bin32/ivrrendermodels/ivrrendermodels_005.o bin32/ivrextendeddisplay/ivrextendeddisplay_001.o bin32/ivrtrackedcamera/ivrtrackedcamera_002.o bin32/ivrtrackedcamera/ivrtrackedcamera_003.o bin32/ivrscreenshots/ivrscreenshots_001.o bin32/ivrresources/ivrresources_001.o bin32/ivrdrivermanager/ivrdrivermanager_001.o -Lopenvr/bin/linux32 -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -m32 -shared -lopenvr_api
ld: Relocatable linking with relocations from format elf64-x86-64 (/usr/lib/x86_64-linux-gnu/wine-development/libwinecrt0.a(dll_entry.o)) to format elf32-i386 (openvr_api.obJ9kA.o) is not supported
winebuild: ld failed with status 1
winegcc: /usr/lib/wine-development/winebuild failed
Makefile:107: recipe for target 'bin32/openvr_api.dll.so' failed
make: *** [bin32/openvr_api.dll.so] Error 2
`

**Comment by ghost** [comment]
Oh, yes, I do have those two packages installed.

**Comment by roothorick** [comment]
I assume you accidentally closed the issue?

Edit the top two lines of the Makefile to match the Wine installation. Based on the paths in the error it's probably something like

    WINEPATH_32=/usr/lib/i386-linux-gnu/wine-development
    WINEPATH_64=/usr/lib/x86_64-linux-gnu/wine-development

I'll worry about setting up some kind of configurator to handle this transparently later.

**Comment by ghost** [comment]
Oops, that wasn't on purpose no :smile: 
Your fix didn't work.
But I had a look at the /opt folder and tried to use /opt/wine-devel and it worked.
Keep in mind that wine-stable is also there but I did not try using it.

This will probably vary from distro to distro.
Now, to see if I can figure out how to use this :grin:

**Comment by roothorick** [comment]
Good to see you got it finally :)

Don't expect much. The "hellovr" example and Janus VR are the only things I've had so much as boot, so far.
