### ISSUE TITLE
Collaboration with DXVK?

### ISSUE THREAD

**Issue by poVoq** [roothorick/WineOpenVR#4]
See: https://github.com/doitsujin/dxvk

My guess is that running most Windows SteamVR games (DX11 I suppose) though this on Vulkan would improve compatibility with Linux SteamVR?

**Comment by roothorick** [comment]
That's pretty much the plan at this stage. I have an open issue on their tracker about it here https://github.com/doitsujin/dxvk/issues/27

Then there was an extensive argument about mixed Direct3D versions in this issue: https://github.com/doitsujin/dxvk/issues/38 which implied that there needs to be more extensive integration APIs to allow e.g. dxvk and VK9 to integrate with each other and function within the same Vulkan instance. I was hoping that someone that knows more about DirectX than me would make that come to fruition, which would then work well for WOVR. But that thought appears to have flatly died.

I am increasingly considering just taking matters into my own hands at this point.

**Comment by roothorick** [comment]
I made a separate issue https://github.com/doitsujin/dxvk/issues/73 directly asking about dxvk/VK9 integration. I'll decide what to do in a week based on what answers I get.

**Comment by roothorick** [comment]
Closing as this should all be covered under #1
